### ISSUE TITLE
Problems loading RL2 in Internet Explorer

### ISSUE THREAD

**Issue by hloliver** [PTFS-Europe/rebus-list-2#326]
RL2 isn't loading properly for us in IE11 - certain icons/images are missing ie Browse, hierarchy, find item on shelf
I've tried several pcs, and cleared browser history, forced reload etc but none have worked.
can you take a look?
thanks
Helen

![browse_icon_missing_from_ie](https://cloud.githubusercontent.com/assets/12201255/25843884/baded10e-34a0-11e7-867d-98cffea894a6.png)

![browse icon missing from ie_2](https://cloud.githubusercontent.com/assets/12201255/25843896/c3a6d2a0-34a0-11e7-8909-8b9911124660.png)
![browse_icon_missing_from_ie_3](https://cloud.githubusercontent.com/assets/12201255/25844100/56228084-34a1-11e7-9c00-be99dafe7bf5.png)

**Comment by AndrewIsh** [comment]
Hi Helen

This should now be fixed. Can you confirm that it is, I'll then close this issue.

Many thanks
Andrew

**Comment by hloliver** [comment]
Hi Andrew

Still seeing the issue here! I’ve cleared the browser history/forced refresh but it hasn’t helped

bw
Helen

**Comment by AndrewIsh** [comment]
Hi Helen

What version of Internet Explorer are you using?

Many thanks
Andrew

**Comment by hloliver** [comment]
11.0.9600.18639

Thanks
Helen

**Comment by AndrewIsh** [comment]
Hi Helen

Thanks for that. This is a known problem with Internet Explorer and the types of icons we're using. I've created a fix, we'll push it out with the next scheduled update next Monday night (15th).

Many thanks
Andrew

**Comment by hloliver** [comment]
Hi Andrew - we're still not getting the icons on IE, I've cleared the browser history and forced refresh but still nothing!
Helen

**Comment by mrenvoize** [comment]
Hi Helen, 

The fix was only rolled out at lunch time today I'm afraid (we found a last minute issue to fix before we rolled this morning).

You should find it working correctly now, but do let us know if that is not the case.

Many thanks, 

Martin

**Comment by AndrewIsh** [comment]
Hi Helen

Just to confirm, I just tested in Internet Explorer here and the icons are displaying correctly.

![capture](https://cloud.githubusercontent.com/assets/9194223/26109654/e1647a0c-3a47-11e7-8082-298a0b0a6720.PNG)

Many thanks
Andrew

**Comment by hloliver** [comment]
all good now - thanks!

**Comment by AndrewIsh** [comment]
Excellent. I'll close this issue. If you see any further problems with this, feel free to re-open it.

Many thanks
Andrew
